# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sop < Formula
  desc ""
  homepage "https://github.com/marcosy/homebrew-tap"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcosy/sop/releases/download/v1.0.1/sop_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "f7aa8771a17b238a5654fc2daac50a4c67112f7eb7e59a393f45e8d04be14ee1"

      def install
        bin.install "sop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcosy/sop/releases/download/v1.0.1/sop_1.0.1_Darwin_arm64.tar.gz"
      sha256 "e47cd9cdc0ea757b05368afec6dcf6774a637a091e95d0345c9930c07cda86fb"

      def install
        bin.install "sop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/marcosy/sop/releases/download/v1.0.1/sop_1.0.1_Linux_x86_64.tar.gz"
      sha256 "7398acd40dc934b6bf5aa2a56dc5b2a273229265c648e2a76555c2a009ae19b2"

      def install
        bin.install "sop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcosy/sop/releases/download/v1.0.1/sop_1.0.1_Linux_arm64.tar.gz"
      sha256 "fa02eb98f97edac3d6e91fb53a358f6d4d7437e1b0fc204069a68d31f8123ef6"

      def install
        bin.install "sop"
      end
    end
  end
end
